# Generated by Django 3.1.7 on 2021-03-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_tweetarticle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetarticle',
            name='image',
            field=models.IntegerField(),
        ),
    ]
