# Generated by Django 3.1.7 on 2021-03-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20210310_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetarticle',
            name='image',
        ),
        migrations.AddField(
            model_name='tweetarticle',
            name='images',
            field=models.ImageField(default=999, upload_to=''),
            preserve_default=False,
        ),
    ]
