# Generated by Django 3.1.7 on 2021-03-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20210310_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetarticle',
            name='images',
        ),
        migrations.AddField(
            model_name='tweetarticle',
            name='image',
            field=models.FileField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
