# Generated by Django 3.1.7 on 2021-03-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20210310_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetarticle',
            name='image',
        ),
        migrations.AddField(
            model_name='tweetarticle',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='tweetarticle',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='tweetarticle',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='tweetarticle',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='tweetarticle',
            name='content',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='tweetarticle',
            name='posting_time',
            field=models.DateTimeField(max_length=200, null=True),
        ),
    ]
