# Generated by Django 3.1.7 on 2021-03-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20210311_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTweet',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('kanriid', models.CharField(max_length=5)),
                ('tweet', models.CharField(max_length=280)),
                ('tw_flg', models.CharField(max_length=1)),
                ('updated', models.CharField(max_length=14)),
                ('reserve_date', models.CharField(max_length=14)),
                ('img_path1', models.CharField(blank=True, max_length=200, null=True)),
                ('img_path2', models.CharField(blank=True, max_length=200, null=True)),
                ('img_path3', models.CharField(blank=True, max_length=200, null=True)),
                ('img_path4', models.CharField(blank=True, max_length=200, null=True)),
                ('tweet_url', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('info_url', models.CharField(blank=True, max_length=200, null=True)),
                ('tweet_id', models.CharField(blank=True, max_length=30, null=True)),
                ('gif_path', models.CharField(blank=True, max_length=200, null=True)),
                ('touhyou', models.CharField(blank=True, max_length=30, null=True)),
                ('emoji', models.CharField(blank=True, max_length=30, null=True)),
                ('hashtag', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'auto_tweet',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TweetArticle',
        ),
    ]
