# Generated by Django 3.1.7 on 2021-03-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_auto_20210313_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('kanriid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('disp_name', models.CharField(max_length=50)),
                ('url', models.CharField(db_column='URL', max_length=100)),
                ('latest_tweet', models.CharField(max_length=16)),
                ('latest_tweet_seq', models.IntegerField()),
                ('latest_tweet_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ACCOUNT_INFO',
                'managed': False,
            },
        ),
    ]
