# Generated by Django 3.1.7 on 2021-03-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_accountinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followlist',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('kanriid', models.CharField(max_length=5)),
                ('follow_flg', models.CharField(max_length=1)),
                ('guid', models.CharField(blank=True, max_length=30, null=True)),
                ('point', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'follow_list',
                'managed': False,
            },
        ),
    ]
