# Generated by Django 3.1.7 on 2021-03-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_auto_20210318_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='followlist',
            name='screenname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
